db: 192.168.0.235
port: 27017
db_name : gv_test
coll_comm : community_test
building : building_test
house : house_test
rabbitmq_host : 192.168.0.235
rabbitmq_port : 5673
redies_host : 192.168.0.235
redis_port : 6699
redis_db : 0