# 测试
mongo:
    host: 192.168.0.136
    port: 27017
    db_name : fangjia_youfang
    coll_comm : news_library_1
    url_code : article_id
    comments : comments
mongo_235:
    config_host: 114.80.150.196
    port: 27017
    config_db : test
    coll_detail : detail_config
    coll_list : list_config
    clean : clean

rabbitmq_host : 114.80.150.196
rabbitmq_port : 5673
redies_host : 114.80.150.196
redis_port : 6379
redis_db : 0

#
## 正式
#mongo:
#    host: 222.73.196.143
#    port: 27017
#    db_name : fangjia_youfang
#    coll_comm : news_library_1
#    url_code : article_id
#    comments : comments
#rabbitmq_host : 192.168.0.191
#rabbitmq_port : 5673
#redies_host : 192.168.0.191
#redis_port : 6379
#redis_db : 0
