# 测试
mongo:
    host: 192.168.0.136
    port: 27017
    db_name : fangjia_youfang
    coll_comm : news_library
    url_code : article_id
    comments : comments
rabbitmq_host : 192.168.0.191
rabbitmq_port : 5673
redies_host : 192.168.0.235
redis_port : 6699
redis_db : 0

#
## 正式
#mongo:
#    host: 222.73.196.143
#    port: 27017
#    db_name : fangjia_youfang
#    coll_comm : news_library
#    url_code : article_id
#    comments : comments
#rabbitmq_host : 192.168.0.191
#rabbitmq_port : 5673
#redies_host : 192.168.0.191
#redis_port : 6379
#redis_db : 0
